;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Item.Category.Ingredients",NewTagName="Item.Category.Ingredient")
+GameplayTagList=(Tag="CraftSystem.Blocks.ManualPause",DevComment="")
+GameplayTagList=(Tag="CraftSystem.Blocks.NoOperator",DevComment="")
+GameplayTagList=(Tag="CraftSystem.Blocks.NoResources",DevComment="")
+GameplayTagList=(Tag="CraftSystem.InvTags.Fuel",DevComment="")
+GameplayTagList=(Tag="CraftSystem.InvTags.Input",DevComment="")
+GameplayTagList=(Tag="CraftSystem.InvTags.Output",DevComment="")
+GameplayTagList=(Tag="Equipment.Slot.Chest",DevComment="")
+GameplayTagList=(Tag="Equipment.Slot.QuickSlot1",DevComment="")
+GameplayTagList=(Tag="Equipment.Slot.QuickSlot2",DevComment="")
+GameplayTagList=(Tag="Equipment.Slot.QuickSlot3",DevComment="")
+GameplayTagList=(Tag="Equipment.Slot.Weapon",DevComment="")
+GameplayTagList=(Tag="Item.Category.Armor",DevComment="")
+GameplayTagList=(Tag="Item.Category.Consumable",DevComment="")
+GameplayTagList=(Tag="Item.Category.Ingredient",DevComment="")
+GameplayTagList=(Tag="Item.Category.Money",DevComment="")
+GameplayTagList=(Tag="Item.Category.Weapon",DevComment="")
+GameplayTagList=(Tag="UI.ButtonsCraft",DevComment="")
+GameplayTagList=(Tag="UI.ButtonsCraft.AddTask",DevComment="")
+GameplayTagList=(Tag="UI.Invenza",DevComment="")
+GameplayTagList=(Tag="UI.Invenza.Equipment",DevComment="")
+GameplayTagList=(Tag="UI.Invenza.Hotbar",DevComment="")
+GameplayTagList=(Tag="UI.Invenza.MainInventory",DevComment="")
+GameplayTagList=(Tag="UI.Invenza.MainLootInventory",DevComment="")
+GameplayTagList=(Tag="UI.Invenza.SecondInv",DevComment="")
+GameplayTagList=(Tag="UI.Invenza.VendorInventory",DevComment="")
+GameplayTagList=(Tag="UI.Layer.Game",DevComment="")
+GameplayTagList=(Tag="UI.Layer.GameMenu",DevComment="")
+GameplayTagList=(Tag="UI.Layer.Menu",DevComment="")
+GameplayTagList=(Tag="UI.Layer.Modal",DevComment="")
+GameplayTagList=(Tag="UI.Modal.Action.Cancel",DevComment="")
+GameplayTagList=(Tag="UI.Modal.Action.Delete",DevComment="")
+GameplayTagList=(Tag="UI.Modal.Action.Drop",DevComment="")
+GameplayTagList=(Tag="UI.Modal.Action.Equip",DevComment="")
+GameplayTagList=(Tag="UI.Modal.Action.No",DevComment="")
+GameplayTagList=(Tag="UI.Modal.Action.OK",DevComment="")
+GameplayTagList=(Tag="UI.Modal.Action.Split",DevComment="")
+GameplayTagList=(Tag="UI.Modal.Action.UnEquip",DevComment="")
+GameplayTagList=(Tag="UI.Modal.Action.Use",DevComment="")
+GameplayTagList=(Tag="UI.Modal.Action.Yes",DevComment="")

